In [2]:
import litminion as lm

In [3]:
lm.set_email("rebecca.sessa@studio.unibo.it")

In [4]:
#download corpus

df = lm.download_pubmed(
    query="JAK inhibitor",
    max_results=10,
)

df.head()

,PMID,Title,Abstract,Journal,Year,Authors,PublicationType
0,42365190,Comment on: The use of Janus kinase inhibitors...,,"Eye (London, England)",2026,Natasa Vidovic Valentincic; Matija Tomsic; Pol...,Letter
1,42364375,Efficacy and safety of JAK inhibitors in Behçe...,Given the active role of the JAK signaling pat...,Seminars in arthritis and rheumatism,2026,Bercemhan Sulu; Sinem Nihal Esatoglu; Gozde Ku...,Journal Article
2,42364256,Ocular sarcoidosis: from clinical signs to tar...,Ocular sarcoidosis is a frequent manifestation...,Current opinion in immunology,2026,Thomas El Jammal; Robin Jacquot; Stéphane Abra...,Journal Article; Review
3,42364020,Filgotinib induces apoptosis in colorectal can...,Colorectal cancer remains a significant health...,Molecular biology reports,2026,Ying Zhou; Zhen Li; Yanyang Zhao; Chenmeng Li;...,Journal Article
4,42362915,Clinical and prognostic significance of concom...,There is growing interest in the association b...,Annals of hematology,2026,Alessandro Costa; Olga Mulas; Marianna Greco; ...,Journal Article

In [5]:
#dataset info

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PMID             10 non-null     str
 1   Title            10 non-null     str
 2   Abstract         10 non-null     str
 3   Journal          10 non-null     str
 4   Year             10 non-null     str
 5   Authors          10 non-null     str
 6   PublicationType  10 non-null     str
dtypes: str(7)
memory usage: 692.0 bytes

In [6]:
#missing values

df.isna().sum()

PMID               0
Title              0
Abstract           0
Journal            0
Year               0
Authors            0
PublicationType    0
dtype: int64

In [7]:
#publication types
df["PublicationType"].value_counts()

PublicationType
Journal Article            8
Letter                     1
Journal Article; Review    1
Name: count, dtype: int64

In [8]:
df[df["Abstract"] == ""]

,PMID,Title,Abstract,Journal,Year,Authors,PublicationType
0,42365190,Comment on: The use of Janus kinase inhibitors...,,"Eye (London, England)",2026,Natasa Vidovic Valentincic; Matija Tomsic; Pol...,Letter